// whitelist_recursively = false
/* automatically generated by rust-bindgen */

pub type mbedtls_mpi_uint = u64;
#[repr(C)]
pub struct mbedtls_mpi {
    ///<  integer sign
    pub s: ::std::os::raw::c_int,
    ///<  total # of limbs
    pub n: usize,
    ///<  pointer to limbs
    pub p: *mut mbedtls_mpi_uint,
}