/* automatically generated by rust-bindgen 0.71.1 */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub mod std {
        #[allow(unused_imports)]
        use self::super::super::root;
        #[repr(C)]
        #[derive(Debug, Copy, Clone)]
        pub struct fbstring_core {
            pub _address: u8,
        }
        pub type fbstring_core_category_type = u8;
        pub type fbstring_core_Category = root::std::fbstring_core_category_type;
    }
}
