/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MyClass<temp> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<temp>>,
    pub options: temp,
}
unsafe extern "C" {
    pub static mut first: *mut MyClass<temp>;
}
