/* automatically generated by rust-bindgen 0.71.1 */

pub type Tcl_FSDupInternalRepProc = ::std::option::Option<unsafe extern "C" fn()>;
unsafe extern "C" {
    #[link_name = "\u{1}__Z23TclNativeDupInternalRepv"]
    pub fn TclNativeDupInternalRep();
}
