/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub static mut a: *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub static mut b: *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub static c: *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub static d: *const ::std::os::raw::c_char;
}
