/* automatically generated by rust-bindgen */

extern "C" {
    #[link_name = "a"]
    pub static mut a: *mut ::std::os::raw::c_char;
}
extern "C" {
    #[link_name = "b"]
    pub static mut b: *const ::std::os::raw::c_char;
}
extern "C" {
    #[link_name = "c"]
    pub static c: *const ::std::os::raw::c_char;
}
extern "C" {
    #[link_name = "d"]
    pub static d: *const ::std::os::raw::c_char;
}