/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct foo {
    pub type_: ::std::os::raw::c_int,
    pub type_: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of foo"][::std::mem::size_of::<foo>() - 8usize];
    ["Alignment of foo"][::std::mem::align_of::<foo>() - 4usize];
    ["Offset of field: foo::type_"][::std::mem::offset_of!(foo, type_) - 0usize];
    ["Offset of field: foo::type_"][::std::mem::offset_of!(foo, type_) - 4usize];
};
