/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
pub struct __BindgenUnionField<T>(::std::marker::PhantomData<T>);
impl<T> __BindgenUnionField<T> {
    #[inline]
    pub const fn new() -> Self {
        __BindgenUnionField(::std::marker::PhantomData)
    }
    #[inline]
    pub unsafe fn as_ref(&self) -> &T {
        ::std::mem::transmute(self)
    }
    #[inline]
    pub unsafe fn as_mut(&mut self) -> &mut T {
        ::std::mem::transmute(self)
    }
}
impl<T> ::std::default::Default for __BindgenUnionField<T> {
    #[inline]
    fn default() -> Self {
        Self::new()
    }
}
impl<T> ::std::clone::Clone for __BindgenUnionField<T> {
    #[inline]
    fn clone(&self) -> Self {
        *self
    }
}
impl<T> ::std::marker::Copy for __BindgenUnionField<T> {}
impl<T> ::std::fmt::Debug for __BindgenUnionField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__BindgenUnionField")
    }
}
impl<T> ::std::hash::Hash for __BindgenUnionField<T> {
    fn hash<H: ::std::hash::Hasher>(&self, _state: &mut H) {}
}
impl<T> ::std::cmp::PartialEq for __BindgenUnionField<T> {
    fn eq(&self, _other: &__BindgenUnionField<T>) -> bool {
        true
    }
}
impl<T> ::std::cmp::Eq for __BindgenUnionField<T> {}
pub const FMOD_STUDIO_LOAD_MEMORY_ALIGNMENT: u32 = 32;
pub const FMOD_STUDIO_INIT_NORMAL: u32 = 0;
pub const FMOD_STUDIO_INIT_LIVEUPDATE: u32 = 1;
pub const FMOD_STUDIO_INIT_ALLOW_MISSING_PLUGINS: u32 = 2;
pub const FMOD_STUDIO_INIT_SYNCHRONOUS_UPDATE: u32 = 4;
pub const FMOD_STUDIO_INIT_DEFERRED_CALLBACKS: u32 = 8;
pub const FMOD_STUDIO_INIT_LOAD_FROM_UPDATE: u32 = 16;
pub const FMOD_STUDIO_INIT_MEMORY_TRACKING: u32 = 32;
pub const FMOD_STUDIO_PARAMETER_READONLY: u32 = 1;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC: u32 = 2;
pub const FMOD_STUDIO_PARAMETER_GLOBAL: u32 = 4;
pub const FMOD_STUDIO_PARAMETER_DISCRETE: u32 = 8;
pub const FMOD_STUDIO_PARAMETER_LABELED: u32 = 16;
pub const FMOD_STUDIO_SYSTEM_CALLBACK_PREUPDATE: u32 = 1;
pub const FMOD_STUDIO_SYSTEM_CALLBACK_POSTUPDATE: u32 = 2;
pub const FMOD_STUDIO_SYSTEM_CALLBACK_BANK_UNLOAD: u32 = 4;
pub const FMOD_STUDIO_SYSTEM_CALLBACK_LIVEUPDATE_CONNECTED: u32 = 8;
pub const FMOD_STUDIO_SYSTEM_CALLBACK_LIVEUPDATE_DISCONNECTED: u32 = 16;
pub const FMOD_STUDIO_SYSTEM_CALLBACK_ALL: u32 = 4294967295;
pub const FMOD_STUDIO_EVENT_CALLBACK_CREATED: u32 = 1;
pub const FMOD_STUDIO_EVENT_CALLBACK_DESTROYED: u32 = 2;
pub const FMOD_STUDIO_EVENT_CALLBACK_STARTING: u32 = 4;
pub const FMOD_STUDIO_EVENT_CALLBACK_STARTED: u32 = 8;
pub const FMOD_STUDIO_EVENT_CALLBACK_RESTARTED: u32 = 16;
pub const FMOD_STUDIO_EVENT_CALLBACK_STOPPED: u32 = 32;
pub const FMOD_STUDIO_EVENT_CALLBACK_START_FAILED: u32 = 64;
pub const FMOD_STUDIO_EVENT_CALLBACK_CREATE_PROGRAMMER_SOUND: u32 = 128;
pub const FMOD_STUDIO_EVENT_CALLBACK_DESTROY_PROGRAMMER_SOUND: u32 = 256;
pub const FMOD_STUDIO_EVENT_CALLBACK_PLUGIN_CREATED: u32 = 512;
pub const FMOD_STUDIO_EVENT_CALLBACK_PLUGIN_DESTROYED: u32 = 1024;
pub const FMOD_STUDIO_EVENT_CALLBACK_TIMELINE_MARKER: u32 = 2048;
pub const FMOD_STUDIO_EVENT_CALLBACK_TIMELINE_BEAT: u32 = 4096;
pub const FMOD_STUDIO_EVENT_CALLBACK_SOUND_PLAYED: u32 = 8192;
pub const FMOD_STUDIO_EVENT_CALLBACK_SOUND_STOPPED: u32 = 16384;
pub const FMOD_STUDIO_EVENT_CALLBACK_REAL_TO_VIRTUAL: u32 = 32768;
pub const FMOD_STUDIO_EVENT_CALLBACK_VIRTUAL_TO_REAL: u32 = 65536;
pub const FMOD_STUDIO_EVENT_CALLBACK_START_EVENT_COMMAND: u32 = 131072;
pub const FMOD_STUDIO_EVENT_CALLBACK_NESTED_TIMELINE_BEAT: u32 = 262144;
pub const FMOD_STUDIO_EVENT_CALLBACK_ALL: u32 = 4294967295;
pub const FMOD_STUDIO_LOAD_BANK_NORMAL: u32 = 0;
pub const FMOD_STUDIO_LOAD_BANK_NONBLOCKING: u32 = 1;
pub const FMOD_STUDIO_LOAD_BANK_DECOMPRESS_SAMPLES: u32 = 2;
pub const FMOD_STUDIO_LOAD_BANK_UNENCRYPTED: u32 = 4;
pub const FMOD_STUDIO_COMMANDCAPTURE_NORMAL: u32 = 0;
pub const FMOD_STUDIO_COMMANDCAPTURE_FILEFLUSH: u32 = 1;
pub const FMOD_STUDIO_COMMANDCAPTURE_SKIP_INITIAL_STATE: u32 = 2;
pub const FMOD_STUDIO_COMMANDREPLAY_NORMAL: u32 = 0;
pub const FMOD_STUDIO_COMMANDREPLAY_SKIP_CLEANUP: u32 = 1;
pub const FMOD_STUDIO_COMMANDREPLAY_FAST_FORWARD: u32 = 2;
pub const FMOD_STUDIO_COMMANDREPLAY_SKIP_BANK_LOAD: u32 = 4;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_SYSTEM {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_EVENTDESCRIPTION {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_EVENTINSTANCE {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_BUS {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_VCA {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_BANK {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_COMMANDREPLAY {
    _unused: [u8; 0],
}
pub type FMOD_STUDIO_INITFLAGS = ::std::os::raw::c_uint;
pub type FMOD_STUDIO_PARAMETER_FLAGS = ::std::os::raw::c_uint;
pub type FMOD_STUDIO_SYSTEM_CALLBACK_TYPE = ::std::os::raw::c_uint;
pub type FMOD_STUDIO_EVENT_CALLBACK_TYPE = ::std::os::raw::c_uint;
pub type FMOD_STUDIO_LOAD_BANK_FLAGS = ::std::os::raw::c_uint;
pub type FMOD_STUDIO_COMMANDCAPTURE_FLAGS = ::std::os::raw::c_uint;
pub type FMOD_STUDIO_COMMANDREPLAY_FLAGS = ::std::os::raw::c_uint;
pub const FMOD_STUDIO_LOADING_STATE_UNLOADING: FMOD_STUDIO_LOADING_STATE = 0;
pub const FMOD_STUDIO_LOADING_STATE_UNLOADED: FMOD_STUDIO_LOADING_STATE = 1;
pub const FMOD_STUDIO_LOADING_STATE_LOADING: FMOD_STUDIO_LOADING_STATE = 2;
pub const FMOD_STUDIO_LOADING_STATE_LOADED: FMOD_STUDIO_LOADING_STATE = 3;
pub const FMOD_STUDIO_LOADING_STATE_ERROR: FMOD_STUDIO_LOADING_STATE = 4;
pub const FMOD_STUDIO_LOADING_STATE_FORCEINT: FMOD_STUDIO_LOADING_STATE = 65536;
pub type FMOD_STUDIO_LOADING_STATE = ::std::os::raw::c_uint;
pub const FMOD_STUDIO_LOAD_MEMORY: FMOD_STUDIO_LOAD_MEMORY_MODE = 0;
pub const FMOD_STUDIO_LOAD_MEMORY_POINT: FMOD_STUDIO_LOAD_MEMORY_MODE = 1;
pub const FMOD_STUDIO_LOAD_MEMORY_FORCEINT: FMOD_STUDIO_LOAD_MEMORY_MODE = 65536;
pub type FMOD_STUDIO_LOAD_MEMORY_MODE = ::std::os::raw::c_uint;
pub const FMOD_STUDIO_PARAMETER_GAME_CONTROLLED: FMOD_STUDIO_PARAMETER_TYPE = 0;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE: FMOD_STUDIO_PARAMETER_TYPE = 1;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_CONE_ANGLE: FMOD_STUDIO_PARAMETER_TYPE = 2;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_ORIENTATION: FMOD_STUDIO_PARAMETER_TYPE = 3;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_DIRECTION: FMOD_STUDIO_PARAMETER_TYPE = 4;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_ELEVATION: FMOD_STUDIO_PARAMETER_TYPE = 5;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_LISTENER_ORIENTATION: FMOD_STUDIO_PARAMETER_TYPE = 6;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED: FMOD_STUDIO_PARAMETER_TYPE = 7;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED_ABSOLUTE: FMOD_STUDIO_PARAMETER_TYPE = 8;
pub const FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE_NORMALIZED: FMOD_STUDIO_PARAMETER_TYPE = 9;
pub const FMOD_STUDIO_PARAMETER_MAX: FMOD_STUDIO_PARAMETER_TYPE = 10;
pub const FMOD_STUDIO_PARAMETER_FORCEINT: FMOD_STUDIO_PARAMETER_TYPE = 65536;
pub type FMOD_STUDIO_PARAMETER_TYPE = ::std::os::raw::c_uint;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_INTEGER: FMOD_STUDIO_USER_PROPERTY_TYPE = 0;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_BOOLEAN: FMOD_STUDIO_USER_PROPERTY_TYPE = 1;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_FLOAT: FMOD_STUDIO_USER_PROPERTY_TYPE = 2;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_STRING: FMOD_STUDIO_USER_PROPERTY_TYPE = 3;
pub const FMOD_STUDIO_USER_PROPERTY_TYPE_FORCEINT: FMOD_STUDIO_USER_PROPERTY_TYPE = 65536;
pub type FMOD_STUDIO_USER_PROPERTY_TYPE = ::std::os::raw::c_uint;
pub const FMOD_STUDIO_EVENT_PROPERTY_CHANNELPRIORITY: FMOD_STUDIO_EVENT_PROPERTY = 0;
pub const FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_DELAY: FMOD_STUDIO_EVENT_PROPERTY = 1;
pub const FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_LOOKAHEAD: FMOD_STUDIO_EVENT_PROPERTY = 2;
pub const FMOD_STUDIO_EVENT_PROPERTY_MINIMUM_DISTANCE: FMOD_STUDIO_EVENT_PROPERTY = 3;
pub const FMOD_STUDIO_EVENT_PROPERTY_MAXIMUM_DISTANCE: FMOD_STUDIO_EVENT_PROPERTY = 4;
pub const FMOD_STUDIO_EVENT_PROPERTY_COOLDOWN: FMOD_STUDIO_EVENT_PROPERTY = 5;
pub const FMOD_STUDIO_EVENT_PROPERTY_MAX: FMOD_STUDIO_EVENT_PROPERTY = 6;
pub const FMOD_STUDIO_EVENT_PROPERTY_FORCEINT: FMOD_STUDIO_EVENT_PROPERTY = 65536;
pub type FMOD_STUDIO_EVENT_PROPERTY = ::std::os::raw::c_uint;
pub const FMOD_STUDIO_PLAYBACK_PLAYING: FMOD_STUDIO_PLAYBACK_STATE = 0;
pub const FMOD_STUDIO_PLAYBACK_SUSTAINING: FMOD_STUDIO_PLAYBACK_STATE = 1;
pub const FMOD_STUDIO_PLAYBACK_STOPPED: FMOD_STUDIO_PLAYBACK_STATE = 2;
pub const FMOD_STUDIO_PLAYBACK_STARTING: FMOD_STUDIO_PLAYBACK_STATE = 3;
pub const FMOD_STUDIO_PLAYBACK_STOPPING: FMOD_STUDIO_PLAYBACK_STATE = 4;
pub const FMOD_STUDIO_PLAYBACK_FORCEINT: FMOD_STUDIO_PLAYBACK_STATE = 65536;
pub type FMOD_STUDIO_PLAYBACK_STATE = ::std::os::raw::c_uint;
pub const FMOD_STUDIO_STOP_ALLOWFADEOUT: FMOD_STUDIO_STOP_MODE = 0;
pub const FMOD_STUDIO_STOP_IMMEDIATE: FMOD_STUDIO_STOP_MODE = 1;
pub const FMOD_STUDIO_STOP_FORCEINT: FMOD_STUDIO_STOP_MODE = 65536;
pub type FMOD_STUDIO_STOP_MODE = ::std::os::raw::c_uint;
pub const FMOD_STUDIO_INSTANCETYPE_NONE: FMOD_STUDIO_INSTANCETYPE = 0;
pub const FMOD_STUDIO_INSTANCETYPE_SYSTEM: FMOD_STUDIO_INSTANCETYPE = 1;
pub const FMOD_STUDIO_INSTANCETYPE_EVENTDESCRIPTION: FMOD_STUDIO_INSTANCETYPE = 2;
pub const FMOD_STUDIO_INSTANCETYPE_EVENTINSTANCE: FMOD_STUDIO_INSTANCETYPE = 3;
pub const FMOD_STUDIO_INSTANCETYPE_PARAMETERINSTANCE: FMOD_STUDIO_INSTANCETYPE = 4;
pub const FMOD_STUDIO_INSTANCETYPE_BUS: FMOD_STUDIO_INSTANCETYPE = 5;
pub const FMOD_STUDIO_INSTANCETYPE_VCA: FMOD_STUDIO_INSTANCETYPE = 6;
pub const FMOD_STUDIO_INSTANCETYPE_BANK: FMOD_STUDIO_INSTANCETYPE = 7;
pub const FMOD_STUDIO_INSTANCETYPE_COMMANDREPLAY: FMOD_STUDIO_INSTANCETYPE = 8;
pub const FMOD_STUDIO_INSTANCETYPE_FORCEINT: FMOD_STUDIO_INSTANCETYPE = 65536;
pub type FMOD_STUDIO_INSTANCETYPE = ::std::os::raw::c_uint;
#[repr(C)]
pub struct FMOD_STUDIO_BANK_INFO {
    pub size: ::std::os::raw::c_int,
    pub userdata: *mut ::std::os::raw::c_void,
    pub userdatalength: ::std::os::raw::c_int,
    pub opencallback: FMOD_FILE_OPEN_CALLBACK,
    pub closecallback: FMOD_FILE_CLOSE_CALLBACK,
    pub readcallback: FMOD_FILE_READ_CALLBACK,
    pub seekcallback: FMOD_FILE_SEEK_CALLBACK,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_BANK_INFO"][::std::mem::size_of::<FMOD_STUDIO_BANK_INFO>() - 56usize];
    ["Alignment of FMOD_STUDIO_BANK_INFO"]
        [::std::mem::align_of::<FMOD_STUDIO_BANK_INFO>() - 8usize];
    ["Offset of field: FMOD_STUDIO_BANK_INFO::size"]
        [::std::mem::offset_of!(FMOD_STUDIO_BANK_INFO, size) - 0usize];
    ["Offset of field: FMOD_STUDIO_BANK_INFO::userdata"]
        [::std::mem::offset_of!(FMOD_STUDIO_BANK_INFO, userdata) - 8usize];
    ["Offset of field: FMOD_STUDIO_BANK_INFO::userdatalength"]
        [::std::mem::offset_of!(FMOD_STUDIO_BANK_INFO, userdatalength) - 16usize];
    ["Offset of field: FMOD_STUDIO_BANK_INFO::opencallback"]
        [::std::mem::offset_of!(FMOD_STUDIO_BANK_INFO, opencallback) - 24usize];
    ["Offset of field: FMOD_STUDIO_BANK_INFO::closecallback"]
        [::std::mem::offset_of!(FMOD_STUDIO_BANK_INFO, closecallback) - 32usize];
    ["Offset of field: FMOD_STUDIO_BANK_INFO::readcallback"]
        [::std::mem::offset_of!(FMOD_STUDIO_BANK_INFO, readcallback) - 40usize];
    ["Offset of field: FMOD_STUDIO_BANK_INFO::seekcallback"]
        [::std::mem::offset_of!(FMOD_STUDIO_BANK_INFO, seekcallback) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_PARAMETER_ID {
    pub data1: ::std::os::raw::c_uint,
    pub data2: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_PARAMETER_ID"]
        [::std::mem::size_of::<FMOD_STUDIO_PARAMETER_ID>() - 8usize];
    ["Alignment of FMOD_STUDIO_PARAMETER_ID"]
        [::std::mem::align_of::<FMOD_STUDIO_PARAMETER_ID>() - 4usize];
    ["Offset of field: FMOD_STUDIO_PARAMETER_ID::data1"]
        [::std::mem::offset_of!(FMOD_STUDIO_PARAMETER_ID, data1) - 0usize];
    ["Offset of field: FMOD_STUDIO_PARAMETER_ID::data2"]
        [::std::mem::offset_of!(FMOD_STUDIO_PARAMETER_ID, data2) - 4usize];
};
#[repr(C)]
pub struct FMOD_STUDIO_PARAMETER_DESCRIPTION {
    pub name: *const ::std::os::raw::c_char,
    pub id: FMOD_STUDIO_PARAMETER_ID,
    pub minimum: f32,
    pub maximum: f32,
    pub defaultvalue: f32,
    pub type_: FMOD_STUDIO_PARAMETER_TYPE,
    pub flags: FMOD_STUDIO_PARAMETER_FLAGS,
    pub guid: FMOD_GUID,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_PARAMETER_DESCRIPTION"]
        [::std::mem::size_of::<FMOD_STUDIO_PARAMETER_DESCRIPTION>() - 56usize];
    ["Alignment of FMOD_STUDIO_PARAMETER_DESCRIPTION"]
        [::std::mem::align_of::<FMOD_STUDIO_PARAMETER_DESCRIPTION>() - 8usize];
    ["Offset of field: FMOD_STUDIO_PARAMETER_DESCRIPTION::name"]
        [::std::mem::offset_of!(FMOD_STUDIO_PARAMETER_DESCRIPTION, name) - 0usize];
    ["Offset of field: FMOD_STUDIO_PARAMETER_DESCRIPTION::id"]
        [::std::mem::offset_of!(FMOD_STUDIO_PARAMETER_DESCRIPTION, id) - 8usize];
    ["Offset of field: FMOD_STUDIO_PARAMETER_DESCRIPTION::minimum"]
        [::std::mem::offset_of!(FMOD_STUDIO_PARAMETER_DESCRIPTION, minimum) - 16usize];
    ["Offset of field: FMOD_STUDIO_PARAMETER_DESCRIPTION::maximum"]
        [::std::mem::offset_of!(FMOD_STUDIO_PARAMETER_DESCRIPTION, maximum) - 20usize];
    ["Offset of field: FMOD_STUDIO_PARAMETER_DESCRIPTION::defaultvalue"]
        [::std::mem::offset_of!(FMOD_STUDIO_PARAMETER_DESCRIPTION, defaultvalue) - 24usize];
    ["Offset of field: FMOD_STUDIO_PARAMETER_DESCRIPTION::type_"]
        [::std::mem::offset_of!(FMOD_STUDIO_PARAMETER_DESCRIPTION, type_) - 28usize];
    ["Offset of field: FMOD_STUDIO_PARAMETER_DESCRIPTION::flags"]
        [::std::mem::offset_of!(FMOD_STUDIO_PARAMETER_DESCRIPTION, flags) - 32usize];
    ["Offset of field: FMOD_STUDIO_PARAMETER_DESCRIPTION::guid"]
        [::std::mem::offset_of!(FMOD_STUDIO_PARAMETER_DESCRIPTION, guid) - 36usize];
};
#[repr(C)]
pub struct FMOD_STUDIO_USER_PROPERTY {
    pub name: *const ::std::os::raw::c_char,
    pub type_: FMOD_STUDIO_USER_PROPERTY_TYPE,
    pub __bindgen_anon_1: FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1,
}
#[repr(C)]
pub struct FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1 {
    pub intvalue: __BindgenUnionField<::std::os::raw::c_int>,
    pub boolvalue: __BindgenUnionField<FMOD_BOOL>,
    pub floatvalue: __BindgenUnionField<f32>,
    pub stringvalue: __BindgenUnionField<*const ::std::os::raw::c_char>,
    pub bindgen_union_field: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1"]
        [::std::mem::size_of::<FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1>() - 8usize];
    ["Alignment of FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1"]
        [::std::mem::align_of::<FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1>() - 8usize];
    ["Offset of field: FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1::intvalue"]
        [::std::mem::offset_of!(FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1, intvalue) - 0usize];
    ["Offset of field: FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1::boolvalue"]
        [::std::mem::offset_of!(FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1, boolvalue) - 0usize];
    ["Offset of field: FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1::floatvalue"]
        [::std::mem::offset_of!(FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1, floatvalue) - 0usize];
    ["Offset of field: FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1::stringvalue"]
        [::std::mem::offset_of!(FMOD_STUDIO_USER_PROPERTY__bindgen_ty_1, stringvalue) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_USER_PROPERTY"]
        [::std::mem::size_of::<FMOD_STUDIO_USER_PROPERTY>() - 24usize];
    ["Alignment of FMOD_STUDIO_USER_PROPERTY"]
        [::std::mem::align_of::<FMOD_STUDIO_USER_PROPERTY>() - 8usize];
    ["Offset of field: FMOD_STUDIO_USER_PROPERTY::name"]
        [::std::mem::offset_of!(FMOD_STUDIO_USER_PROPERTY, name) - 0usize];
    ["Offset of field: FMOD_STUDIO_USER_PROPERTY::type_"]
        [::std::mem::offset_of!(FMOD_STUDIO_USER_PROPERTY, type_) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES {
    pub name: *const ::std::os::raw::c_char,
    pub sound: *mut FMOD_SOUND,
    pub subsoundIndex: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES"]
        [::std::mem::size_of::<FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES>() - 24usize];
    ["Alignment of FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES"]
        [::std::mem::align_of::<FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES>() - 8usize];
    ["Offset of field: FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES::name"]
        [::std::mem::offset_of!(FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES, name) - 0usize];
    ["Offset of field: FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES::sound"]
        [::std::mem::offset_of!(FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES, sound) - 8usize];
    ["Offset of field: FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES::subsoundIndex"]
        [::std::mem::offset_of!(FMOD_STUDIO_PROGRAMMER_SOUND_PROPERTIES, subsoundIndex) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES {
    pub name: *const ::std::os::raw::c_char,
    pub dsp: *mut FMOD_DSP,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES"]
        [::std::mem::size_of::<FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES>() - 16usize];
    ["Alignment of FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES"]
        [::std::mem::align_of::<FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES>() - 8usize];
    ["Offset of field: FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES::name"]
        [::std::mem::offset_of!(FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES, name) - 0usize];
    ["Offset of field: FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES::dsp"]
        [::std::mem::offset_of!(FMOD_STUDIO_PLUGIN_INSTANCE_PROPERTIES, dsp) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES {
    pub name: *const ::std::os::raw::c_char,
    pub position: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES"]
        [::std::mem::size_of::<FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES>() - 16usize];
    ["Alignment of FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES"]
        [::std::mem::align_of::<FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES>() - 8usize];
    ["Offset of field: FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES::name"]
        [::std::mem::offset_of!(FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES, name) - 0usize];
    ["Offset of field: FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES::position"]
        [::std::mem::offset_of!(FMOD_STUDIO_TIMELINE_MARKER_PROPERTIES, position) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES {
    pub bar: ::std::os::raw::c_int,
    pub beat: ::std::os::raw::c_int,
    pub position: ::std::os::raw::c_int,
    pub tempo: f32,
    pub timesignatureupper: ::std::os::raw::c_int,
    pub timesignaturelower: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES"]
        [::std::mem::size_of::<FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES>() - 24usize];
    ["Alignment of FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES"]
        [::std::mem::align_of::<FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES>() - 4usize];
    ["Offset of field: FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES::bar"]
        [::std::mem::offset_of!(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES, bar) - 0usize];
    ["Offset of field: FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES::beat"]
        [::std::mem::offset_of!(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES, beat) - 4usize];
    ["Offset of field: FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES::position"]
        [::std::mem::offset_of!(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES, position) - 8usize];
    ["Offset of field: FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES::tempo"]
        [::std::mem::offset_of!(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES, tempo) - 12usize];
    ["Offset of field: FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES::timesignatureupper"][::std::mem::offset_of!(
        FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES,
        timesignatureupper
    ) - 16usize];
    ["Offset of field: FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES::timesignaturelower"][::std::mem::offset_of!(
        FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES,
        timesignaturelower
    ) - 20usize];
};
#[repr(C)]
pub struct FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES {
    pub eventid: FMOD_GUID,
    pub properties: FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES"]
        [::std::mem::size_of::<FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES>() - 40usize];
    ["Alignment of FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES"]
        [::std::mem::align_of::<FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES>() - 4usize];
    ["Offset of field: FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES::eventid"]
        [::std::mem::offset_of!(FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES, eventid) - 0usize];
    ["Offset of field: FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES::properties"]
        [::std::mem::offset_of!(FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES, properties) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_ADVANCEDSETTINGS {
    pub cbsize: ::std::os::raw::c_int,
    pub commandqueuesize: ::std::os::raw::c_uint,
    pub handleinitialsize: ::std::os::raw::c_uint,
    pub studioupdateperiod: ::std::os::raw::c_int,
    pub idlesampledatapoolsize: ::std::os::raw::c_int,
    pub streamingscheduledelay: ::std::os::raw::c_uint,
    pub encryptionkey: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_ADVANCEDSETTINGS"]
        [::std::mem::size_of::<FMOD_STUDIO_ADVANCEDSETTINGS>() - 32usize];
    ["Alignment of FMOD_STUDIO_ADVANCEDSETTINGS"]
        [::std::mem::align_of::<FMOD_STUDIO_ADVANCEDSETTINGS>() - 8usize];
    ["Offset of field: FMOD_STUDIO_ADVANCEDSETTINGS::cbsize"]
        [::std::mem::offset_of!(FMOD_STUDIO_ADVANCEDSETTINGS, cbsize) - 0usize];
    ["Offset of field: FMOD_STUDIO_ADVANCEDSETTINGS::commandqueuesize"]
        [::std::mem::offset_of!(FMOD_STUDIO_ADVANCEDSETTINGS, commandqueuesize) - 4usize];
    ["Offset of field: FMOD_STUDIO_ADVANCEDSETTINGS::handleinitialsize"]
        [::std::mem::offset_of!(FMOD_STUDIO_ADVANCEDSETTINGS, handleinitialsize) - 8usize];
    ["Offset of field: FMOD_STUDIO_ADVANCEDSETTINGS::studioupdateperiod"]
        [::std::mem::offset_of!(FMOD_STUDIO_ADVANCEDSETTINGS, studioupdateperiod) - 12usize];
    ["Offset of field: FMOD_STUDIO_ADVANCEDSETTINGS::idlesampledatapoolsize"]
        [::std::mem::offset_of!(FMOD_STUDIO_ADVANCEDSETTINGS, idlesampledatapoolsize) - 16usize];
    ["Offset of field: FMOD_STUDIO_ADVANCEDSETTINGS::streamingscheduledelay"]
        [::std::mem::offset_of!(FMOD_STUDIO_ADVANCEDSETTINGS, streamingscheduledelay) - 20usize];
    ["Offset of field: FMOD_STUDIO_ADVANCEDSETTINGS::encryptionkey"]
        [::std::mem::offset_of!(FMOD_STUDIO_ADVANCEDSETTINGS, encryptionkey) - 24usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_CPU_USAGE {
    pub update: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_CPU_USAGE"][::std::mem::size_of::<FMOD_STUDIO_CPU_USAGE>() - 4usize];
    ["Alignment of FMOD_STUDIO_CPU_USAGE"]
        [::std::mem::align_of::<FMOD_STUDIO_CPU_USAGE>() - 4usize];
    ["Offset of field: FMOD_STUDIO_CPU_USAGE::update"]
        [::std::mem::offset_of!(FMOD_STUDIO_CPU_USAGE, update) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_BUFFER_INFO {
    pub currentusage: ::std::os::raw::c_int,
    pub peakusage: ::std::os::raw::c_int,
    pub capacity: ::std::os::raw::c_int,
    pub stallcount: ::std::os::raw::c_int,
    pub stalltime: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_BUFFER_INFO"][::std::mem::size_of::<FMOD_STUDIO_BUFFER_INFO>() - 20usize];
    ["Alignment of FMOD_STUDIO_BUFFER_INFO"]
        [::std::mem::align_of::<FMOD_STUDIO_BUFFER_INFO>() - 4usize];
    ["Offset of field: FMOD_STUDIO_BUFFER_INFO::currentusage"]
        [::std::mem::offset_of!(FMOD_STUDIO_BUFFER_INFO, currentusage) - 0usize];
    ["Offset of field: FMOD_STUDIO_BUFFER_INFO::peakusage"]
        [::std::mem::offset_of!(FMOD_STUDIO_BUFFER_INFO, peakusage) - 4usize];
    ["Offset of field: FMOD_STUDIO_BUFFER_INFO::capacity"]
        [::std::mem::offset_of!(FMOD_STUDIO_BUFFER_INFO, capacity) - 8usize];
    ["Offset of field: FMOD_STUDIO_BUFFER_INFO::stallcount"]
        [::std::mem::offset_of!(FMOD_STUDIO_BUFFER_INFO, stallcount) - 12usize];
    ["Offset of field: FMOD_STUDIO_BUFFER_INFO::stalltime"]
        [::std::mem::offset_of!(FMOD_STUDIO_BUFFER_INFO, stalltime) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_BUFFER_USAGE {
    pub studiocommandqueue: FMOD_STUDIO_BUFFER_INFO,
    pub studiohandle: FMOD_STUDIO_BUFFER_INFO,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_BUFFER_USAGE"]
        [::std::mem::size_of::<FMOD_STUDIO_BUFFER_USAGE>() - 40usize];
    ["Alignment of FMOD_STUDIO_BUFFER_USAGE"]
        [::std::mem::align_of::<FMOD_STUDIO_BUFFER_USAGE>() - 4usize];
    ["Offset of field: FMOD_STUDIO_BUFFER_USAGE::studiocommandqueue"]
        [::std::mem::offset_of!(FMOD_STUDIO_BUFFER_USAGE, studiocommandqueue) - 0usize];
    ["Offset of field: FMOD_STUDIO_BUFFER_USAGE::studiohandle"]
        [::std::mem::offset_of!(FMOD_STUDIO_BUFFER_USAGE, studiohandle) - 20usize];
};
#[repr(C)]
pub struct FMOD_STUDIO_SOUND_INFO {
    pub name_or_data: *const ::std::os::raw::c_char,
    pub mode: FMOD_MODE,
    pub exinfo: FMOD_CREATESOUNDEXINFO,
    pub subsoundindex: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_SOUND_INFO"][::std::mem::size_of::<FMOD_STUDIO_SOUND_INFO>() - 248usize];
    ["Alignment of FMOD_STUDIO_SOUND_INFO"]
        [::std::mem::align_of::<FMOD_STUDIO_SOUND_INFO>() - 8usize];
    ["Offset of field: FMOD_STUDIO_SOUND_INFO::name_or_data"]
        [::std::mem::offset_of!(FMOD_STUDIO_SOUND_INFO, name_or_data) - 0usize];
    ["Offset of field: FMOD_STUDIO_SOUND_INFO::mode"]
        [::std::mem::offset_of!(FMOD_STUDIO_SOUND_INFO, mode) - 8usize];
    ["Offset of field: FMOD_STUDIO_SOUND_INFO::exinfo"]
        [::std::mem::offset_of!(FMOD_STUDIO_SOUND_INFO, exinfo) - 16usize];
    ["Offset of field: FMOD_STUDIO_SOUND_INFO::subsoundindex"]
        [::std::mem::offset_of!(FMOD_STUDIO_SOUND_INFO, subsoundindex) - 240usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_COMMAND_INFO {
    pub commandname: *const ::std::os::raw::c_char,
    pub parentcommandindex: ::std::os::raw::c_int,
    pub framenumber: ::std::os::raw::c_int,
    pub frametime: f32,
    pub instancetype: FMOD_STUDIO_INSTANCETYPE,
    pub outputtype: FMOD_STUDIO_INSTANCETYPE,
    pub instancehandle: ::std::os::raw::c_uint,
    pub outputhandle: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_COMMAND_INFO"]
        [::std::mem::size_of::<FMOD_STUDIO_COMMAND_INFO>() - 40usize];
    ["Alignment of FMOD_STUDIO_COMMAND_INFO"]
        [::std::mem::align_of::<FMOD_STUDIO_COMMAND_INFO>() - 8usize];
    ["Offset of field: FMOD_STUDIO_COMMAND_INFO::commandname"]
        [::std::mem::offset_of!(FMOD_STUDIO_COMMAND_INFO, commandname) - 0usize];
    ["Offset of field: FMOD_STUDIO_COMMAND_INFO::parentcommandindex"]
        [::std::mem::offset_of!(FMOD_STUDIO_COMMAND_INFO, parentcommandindex) - 8usize];
    ["Offset of field: FMOD_STUDIO_COMMAND_INFO::framenumber"]
        [::std::mem::offset_of!(FMOD_STUDIO_COMMAND_INFO, framenumber) - 12usize];
    ["Offset of field: FMOD_STUDIO_COMMAND_INFO::frametime"]
        [::std::mem::offset_of!(FMOD_STUDIO_COMMAND_INFO, frametime) - 16usize];
    ["Offset of field: FMOD_STUDIO_COMMAND_INFO::instancetype"]
        [::std::mem::offset_of!(FMOD_STUDIO_COMMAND_INFO, instancetype) - 20usize];
    ["Offset of field: FMOD_STUDIO_COMMAND_INFO::outputtype"]
        [::std::mem::offset_of!(FMOD_STUDIO_COMMAND_INFO, outputtype) - 24usize];
    ["Offset of field: FMOD_STUDIO_COMMAND_INFO::instancehandle"]
        [::std::mem::offset_of!(FMOD_STUDIO_COMMAND_INFO, instancehandle) - 28usize];
    ["Offset of field: FMOD_STUDIO_COMMAND_INFO::outputhandle"]
        [::std::mem::offset_of!(FMOD_STUDIO_COMMAND_INFO, outputhandle) - 32usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FMOD_STUDIO_MEMORY_USAGE {
    pub exclusive: ::std::os::raw::c_int,
    pub inclusive: ::std::os::raw::c_int,
    pub sampledata: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FMOD_STUDIO_MEMORY_USAGE"]
        [::std::mem::size_of::<FMOD_STUDIO_MEMORY_USAGE>() - 12usize];
    ["Alignment of FMOD_STUDIO_MEMORY_USAGE"]
        [::std::mem::align_of::<FMOD_STUDIO_MEMORY_USAGE>() - 4usize];
    ["Offset of field: FMOD_STUDIO_MEMORY_USAGE::exclusive"]
        [::std::mem::offset_of!(FMOD_STUDIO_MEMORY_USAGE, exclusive) - 0usize];
    ["Offset of field: FMOD_STUDIO_MEMORY_USAGE::inclusive"]
        [::std::mem::offset_of!(FMOD_STUDIO_MEMORY_USAGE, inclusive) - 4usize];
    ["Offset of field: FMOD_STUDIO_MEMORY_USAGE::sampledata"]
        [::std::mem::offset_of!(FMOD_STUDIO_MEMORY_USAGE, sampledata) - 8usize];
};
pub type FMOD_STUDIO_SYSTEM_CALLBACK = ::std::option::Option<
    unsafe extern "C" fn(
        system: *mut FMOD_STUDIO_SYSTEM,
        type_: FMOD_STUDIO_SYSTEM_CALLBACK_TYPE,
        commanddata: *mut ::std::os::raw::c_void,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT,
>;
pub type FMOD_STUDIO_EVENT_CALLBACK = ::std::option::Option<
    unsafe extern "C" fn(
        type_: FMOD_STUDIO_EVENT_CALLBACK_TYPE,
        event: *mut FMOD_STUDIO_EVENTINSTANCE,
        parameters: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT,
>;
pub type FMOD_STUDIO_COMMANDREPLAY_FRAME_CALLBACK = ::std::option::Option<
    unsafe extern "C" fn(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: ::std::os::raw::c_int,
        currenttime: f32,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT,
>;
pub type FMOD_STUDIO_COMMANDREPLAY_LOAD_BANK_CALLBACK = ::std::option::Option<
    unsafe extern "C" fn(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: ::std::os::raw::c_int,
        bankguid: *const FMOD_GUID,
        bankfilename: *const ::std::os::raw::c_char,
        flags: FMOD_STUDIO_LOAD_BANK_FLAGS,
        bank: *mut *mut FMOD_STUDIO_BANK,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT,
>;
pub type FMOD_STUDIO_COMMANDREPLAY_CREATE_INSTANCE_CALLBACK = ::std::option::Option<
    unsafe extern "C" fn(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: ::std::os::raw::c_int,
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        instance: *mut *mut FMOD_STUDIO_EVENTINSTANCE,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT,
>;
unsafe extern "C" {
    pub fn FMOD_Studio_ParseID(
        idstring: *const ::std::os::raw::c_char,
        id: *mut FMOD_GUID,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_Create(
        system: *mut *mut FMOD_STUDIO_SYSTEM,
        headerversion: ::std::os::raw::c_uint,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_IsValid(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_BOOL;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_SetAdvancedSettings(
        system: *mut FMOD_STUDIO_SYSTEM,
        settings: *mut FMOD_STUDIO_ADVANCEDSETTINGS,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetAdvancedSettings(
        system: *mut FMOD_STUDIO_SYSTEM,
        settings: *mut FMOD_STUDIO_ADVANCEDSETTINGS,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_Initialize(
        system: *mut FMOD_STUDIO_SYSTEM,
        maxchannels: ::std::os::raw::c_int,
        studioflags: FMOD_STUDIO_INITFLAGS,
        flags: FMOD_INITFLAGS,
        extradriverdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_Release(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_Update(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetCoreSystem(
        system: *mut FMOD_STUDIO_SYSTEM,
        coresystem: *mut *mut FMOD_SYSTEM,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetEvent(
        system: *mut FMOD_STUDIO_SYSTEM,
        pathOrID: *const ::std::os::raw::c_char,
        event: *mut *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetBus(
        system: *mut FMOD_STUDIO_SYSTEM,
        pathOrID: *const ::std::os::raw::c_char,
        bus: *mut *mut FMOD_STUDIO_BUS,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetVCA(
        system: *mut FMOD_STUDIO_SYSTEM,
        pathOrID: *const ::std::os::raw::c_char,
        vca: *mut *mut FMOD_STUDIO_VCA,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetBank(
        system: *mut FMOD_STUDIO_SYSTEM,
        pathOrID: *const ::std::os::raw::c_char,
        bank: *mut *mut FMOD_STUDIO_BANK,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetEventByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: *const FMOD_GUID,
        event: *mut *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetBusByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: *const FMOD_GUID,
        bus: *mut *mut FMOD_STUDIO_BUS,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetVCAByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: *const FMOD_GUID,
        vca: *mut *mut FMOD_STUDIO_VCA,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetBankByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: *const FMOD_GUID,
        bank: *mut *mut FMOD_STUDIO_BANK,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetSoundInfo(
        system: *mut FMOD_STUDIO_SYSTEM,
        key: *const ::std::os::raw::c_char,
        info: *mut FMOD_STUDIO_SOUND_INFO,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetParameterDescriptionByName(
        system: *mut FMOD_STUDIO_SYSTEM,
        name: *const ::std::os::raw::c_char,
        parameter: *mut FMOD_STUDIO_PARAMETER_DESCRIPTION,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetParameterDescriptionByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: FMOD_STUDIO_PARAMETER_ID,
        parameter: *mut FMOD_STUDIO_PARAMETER_DESCRIPTION,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetParameterLabelByName(
        system: *mut FMOD_STUDIO_SYSTEM,
        name: *const ::std::os::raw::c_char,
        labelindex: ::std::os::raw::c_int,
        label: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetParameterLabelByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: FMOD_STUDIO_PARAMETER_ID,
        labelindex: ::std::os::raw::c_int,
        label: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetParameterByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: FMOD_STUDIO_PARAMETER_ID,
        value: *mut f32,
        finalvalue: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_SetParameterByID(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: FMOD_STUDIO_PARAMETER_ID,
        value: f32,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_SetParameterByIDWithLabel(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: FMOD_STUDIO_PARAMETER_ID,
        label: *const ::std::os::raw::c_char,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_SetParametersByIDs(
        system: *mut FMOD_STUDIO_SYSTEM,
        ids: *const FMOD_STUDIO_PARAMETER_ID,
        values: *mut f32,
        count: ::std::os::raw::c_int,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetParameterByName(
        system: *mut FMOD_STUDIO_SYSTEM,
        name: *const ::std::os::raw::c_char,
        value: *mut f32,
        finalvalue: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_SetParameterByName(
        system: *mut FMOD_STUDIO_SYSTEM,
        name: *const ::std::os::raw::c_char,
        value: f32,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_SetParameterByNameWithLabel(
        system: *mut FMOD_STUDIO_SYSTEM,
        name: *const ::std::os::raw::c_char,
        label: *const ::std::os::raw::c_char,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_LookupID(
        system: *mut FMOD_STUDIO_SYSTEM,
        path: *const ::std::os::raw::c_char,
        id: *mut FMOD_GUID,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_LookupPath(
        system: *mut FMOD_STUDIO_SYSTEM,
        id: *const FMOD_GUID,
        path: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetNumListeners(
        system: *mut FMOD_STUDIO_SYSTEM,
        numlisteners: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_SetNumListeners(
        system: *mut FMOD_STUDIO_SYSTEM,
        numlisteners: ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetListenerAttributes(
        system: *mut FMOD_STUDIO_SYSTEM,
        index: ::std::os::raw::c_int,
        attributes: *mut FMOD_3D_ATTRIBUTES,
        attenuationposition: *mut FMOD_VECTOR,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_SetListenerAttributes(
        system: *mut FMOD_STUDIO_SYSTEM,
        index: ::std::os::raw::c_int,
        attributes: *const FMOD_3D_ATTRIBUTES,
        attenuationposition: *const FMOD_VECTOR,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetListenerWeight(
        system: *mut FMOD_STUDIO_SYSTEM,
        index: ::std::os::raw::c_int,
        weight: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_SetListenerWeight(
        system: *mut FMOD_STUDIO_SYSTEM,
        index: ::std::os::raw::c_int,
        weight: f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_LoadBankFile(
        system: *mut FMOD_STUDIO_SYSTEM,
        filename: *const ::std::os::raw::c_char,
        flags: FMOD_STUDIO_LOAD_BANK_FLAGS,
        bank: *mut *mut FMOD_STUDIO_BANK,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_LoadBankMemory(
        system: *mut FMOD_STUDIO_SYSTEM,
        buffer: *const ::std::os::raw::c_char,
        length: ::std::os::raw::c_int,
        mode: FMOD_STUDIO_LOAD_MEMORY_MODE,
        flags: FMOD_STUDIO_LOAD_BANK_FLAGS,
        bank: *mut *mut FMOD_STUDIO_BANK,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_LoadBankCustom(
        system: *mut FMOD_STUDIO_SYSTEM,
        info: *const FMOD_STUDIO_BANK_INFO,
        flags: FMOD_STUDIO_LOAD_BANK_FLAGS,
        bank: *mut *mut FMOD_STUDIO_BANK,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_RegisterPlugin(
        system: *mut FMOD_STUDIO_SYSTEM,
        description: *const FMOD_DSP_DESCRIPTION,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_UnregisterPlugin(
        system: *mut FMOD_STUDIO_SYSTEM,
        name: *const ::std::os::raw::c_char,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_UnloadAll(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_FlushCommands(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_FlushSampleLoading(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_StartCommandCapture(
        system: *mut FMOD_STUDIO_SYSTEM,
        filename: *const ::std::os::raw::c_char,
        flags: FMOD_STUDIO_COMMANDCAPTURE_FLAGS,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_StopCommandCapture(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_LoadCommandReplay(
        system: *mut FMOD_STUDIO_SYSTEM,
        filename: *const ::std::os::raw::c_char,
        flags: FMOD_STUDIO_COMMANDREPLAY_FLAGS,
        replay: *mut *mut FMOD_STUDIO_COMMANDREPLAY,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetBankCount(
        system: *mut FMOD_STUDIO_SYSTEM,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetBankList(
        system: *mut FMOD_STUDIO_SYSTEM,
        array: *mut *mut FMOD_STUDIO_BANK,
        capacity: ::std::os::raw::c_int,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetParameterDescriptionCount(
        system: *mut FMOD_STUDIO_SYSTEM,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetParameterDescriptionList(
        system: *mut FMOD_STUDIO_SYSTEM,
        array: *mut FMOD_STUDIO_PARAMETER_DESCRIPTION,
        capacity: ::std::os::raw::c_int,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetCPUUsage(
        system: *mut FMOD_STUDIO_SYSTEM,
        usage: *mut FMOD_STUDIO_CPU_USAGE,
        usage_core: *mut FMOD_CPU_USAGE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetBufferUsage(
        system: *mut FMOD_STUDIO_SYSTEM,
        usage: *mut FMOD_STUDIO_BUFFER_USAGE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_ResetBufferUsage(system: *mut FMOD_STUDIO_SYSTEM) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_SetCallback(
        system: *mut FMOD_STUDIO_SYSTEM,
        callback: FMOD_STUDIO_SYSTEM_CALLBACK,
        callbackmask: FMOD_STUDIO_SYSTEM_CALLBACK_TYPE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_SetUserData(
        system: *mut FMOD_STUDIO_SYSTEM,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetUserData(
        system: *mut FMOD_STUDIO_SYSTEM,
        userdata: *mut *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_System_GetMemoryUsage(
        system: *mut FMOD_STUDIO_SYSTEM,
        memoryusage: *mut FMOD_STUDIO_MEMORY_USAGE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_IsValid(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_BOOL;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetID(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        id: *mut FMOD_GUID,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetPath(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        path: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetParameterDescriptionCount(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetParameterDescriptionByIndex(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        index: ::std::os::raw::c_int,
        parameter: *mut FMOD_STUDIO_PARAMETER_DESCRIPTION,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetParameterDescriptionByName(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        name: *const ::std::os::raw::c_char,
        parameter: *mut FMOD_STUDIO_PARAMETER_DESCRIPTION,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetParameterDescriptionByID(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        id: FMOD_STUDIO_PARAMETER_ID,
        parameter: *mut FMOD_STUDIO_PARAMETER_DESCRIPTION,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetParameterLabelByIndex(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        index: ::std::os::raw::c_int,
        labelindex: ::std::os::raw::c_int,
        label: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetParameterLabelByName(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        name: *const ::std::os::raw::c_char,
        labelindex: ::std::os::raw::c_int,
        label: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetParameterLabelByID(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        id: FMOD_STUDIO_PARAMETER_ID,
        labelindex: ::std::os::raw::c_int,
        label: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetUserPropertyCount(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetUserPropertyByIndex(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        index: ::std::os::raw::c_int,
        property: *mut FMOD_STUDIO_USER_PROPERTY,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetUserProperty(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        name: *const ::std::os::raw::c_char,
        property: *mut FMOD_STUDIO_USER_PROPERTY,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetLength(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        length: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetMinMaxDistance(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        min: *mut f32,
        max: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetSoundSize(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        size: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_IsSnapshot(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        snapshot: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_IsOneshot(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        oneshot: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_IsStream(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        isStream: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_Is3D(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        is3D: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_IsDopplerEnabled(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        doppler: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_HasSustainPoint(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        sustainPoint: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_CreateInstance(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        instance: *mut *mut FMOD_STUDIO_EVENTINSTANCE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetInstanceCount(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetInstanceList(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        array: *mut *mut FMOD_STUDIO_EVENTINSTANCE,
        capacity: ::std::os::raw::c_int,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_LoadSampleData(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_UnloadSampleData(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetSampleLoadingState(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        state: *mut FMOD_STUDIO_LOADING_STATE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_ReleaseAllInstances(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_SetCallback(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        callback: FMOD_STUDIO_EVENT_CALLBACK,
        callbackmask: FMOD_STUDIO_EVENT_CALLBACK_TYPE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_GetUserData(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        userdata: *mut *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventDescription_SetUserData(
        eventdescription: *mut FMOD_STUDIO_EVENTDESCRIPTION,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_IsValid(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
    ) -> FMOD_BOOL;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetDescription(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        description: *mut *mut FMOD_STUDIO_EVENTDESCRIPTION,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetVolume(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        volume: *mut f32,
        finalvolume: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetVolume(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        volume: f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetPitch(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        pitch: *mut f32,
        finalpitch: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetPitch(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        pitch: f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_Get3DAttributes(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        attributes: *mut FMOD_3D_ATTRIBUTES,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_Set3DAttributes(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        attributes: *mut FMOD_3D_ATTRIBUTES,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetListenerMask(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        mask: *mut ::std::os::raw::c_uint,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetListenerMask(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        mask: ::std::os::raw::c_uint,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetProperty(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        index: FMOD_STUDIO_EVENT_PROPERTY,
        value: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetProperty(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        index: FMOD_STUDIO_EVENT_PROPERTY,
        value: f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetReverbLevel(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        index: ::std::os::raw::c_int,
        level: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetReverbLevel(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        index: ::std::os::raw::c_int,
        level: f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetPaused(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        paused: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetPaused(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        paused: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_Start(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_Stop(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        mode: FMOD_STUDIO_STOP_MODE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetTimelinePosition(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        position: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetTimelinePosition(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        position: ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetPlaybackState(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        state: *mut FMOD_STUDIO_PLAYBACK_STATE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetChannelGroup(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        group: *mut *mut FMOD_CHANNELGROUP,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetMinMaxDistance(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        min: *mut f32,
        max: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_Release(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_IsVirtual(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        virtualstate: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetParameterByName(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        name: *const ::std::os::raw::c_char,
        value: *mut f32,
        finalvalue: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetParameterByName(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        name: *const ::std::os::raw::c_char,
        value: f32,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetParameterByNameWithLabel(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        name: *const ::std::os::raw::c_char,
        label: *const ::std::os::raw::c_char,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetParameterByID(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        id: FMOD_STUDIO_PARAMETER_ID,
        value: *mut f32,
        finalvalue: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetParameterByID(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        id: FMOD_STUDIO_PARAMETER_ID,
        value: f32,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetParameterByIDWithLabel(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        id: FMOD_STUDIO_PARAMETER_ID,
        label: *const ::std::os::raw::c_char,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetParametersByIDs(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        ids: *const FMOD_STUDIO_PARAMETER_ID,
        values: *mut f32,
        count: ::std::os::raw::c_int,
        ignoreseekspeed: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_KeyOff(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetCallback(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        callback: FMOD_STUDIO_EVENT_CALLBACK,
        callbackmask: FMOD_STUDIO_EVENT_CALLBACK_TYPE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetUserData(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        userdata: *mut *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_SetUserData(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetCPUUsage(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        exclusive: *mut ::std::os::raw::c_uint,
        inclusive: *mut ::std::os::raw::c_uint,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_EventInstance_GetMemoryUsage(
        eventinstance: *mut FMOD_STUDIO_EVENTINSTANCE,
        memoryusage: *mut FMOD_STUDIO_MEMORY_USAGE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_IsValid(bus: *mut FMOD_STUDIO_BUS) -> FMOD_BOOL;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_GetID(bus: *mut FMOD_STUDIO_BUS, id: *mut FMOD_GUID) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_GetPath(
        bus: *mut FMOD_STUDIO_BUS,
        path: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_GetVolume(
        bus: *mut FMOD_STUDIO_BUS,
        volume: *mut f32,
        finalvolume: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_SetVolume(bus: *mut FMOD_STUDIO_BUS, volume: f32) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_GetPaused(
        bus: *mut FMOD_STUDIO_BUS,
        paused: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_SetPaused(bus: *mut FMOD_STUDIO_BUS, paused: FMOD_BOOL) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_GetMute(bus: *mut FMOD_STUDIO_BUS, mute: *mut FMOD_BOOL) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_SetMute(bus: *mut FMOD_STUDIO_BUS, mute: FMOD_BOOL) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_StopAllEvents(
        bus: *mut FMOD_STUDIO_BUS,
        mode: FMOD_STUDIO_STOP_MODE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_GetPortIndex(
        bus: *mut FMOD_STUDIO_BUS,
        index: *mut FMOD_PORT_INDEX,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_SetPortIndex(
        bus: *mut FMOD_STUDIO_BUS,
        index: FMOD_PORT_INDEX,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_LockChannelGroup(bus: *mut FMOD_STUDIO_BUS) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_UnlockChannelGroup(bus: *mut FMOD_STUDIO_BUS) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_GetChannelGroup(
        bus: *mut FMOD_STUDIO_BUS,
        group: *mut *mut FMOD_CHANNELGROUP,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_GetCPUUsage(
        bus: *mut FMOD_STUDIO_BUS,
        exclusive: *mut ::std::os::raw::c_uint,
        inclusive: *mut ::std::os::raw::c_uint,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bus_GetMemoryUsage(
        bus: *mut FMOD_STUDIO_BUS,
        memoryusage: *mut FMOD_STUDIO_MEMORY_USAGE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_VCA_IsValid(vca: *mut FMOD_STUDIO_VCA) -> FMOD_BOOL;
}
unsafe extern "C" {
    pub fn FMOD_Studio_VCA_GetID(vca: *mut FMOD_STUDIO_VCA, id: *mut FMOD_GUID) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_VCA_GetPath(
        vca: *mut FMOD_STUDIO_VCA,
        path: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_VCA_GetVolume(
        vca: *mut FMOD_STUDIO_VCA,
        volume: *mut f32,
        finalvolume: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_VCA_SetVolume(vca: *mut FMOD_STUDIO_VCA, volume: f32) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_IsValid(bank: *mut FMOD_STUDIO_BANK) -> FMOD_BOOL;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetID(bank: *mut FMOD_STUDIO_BANK, id: *mut FMOD_GUID) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetPath(
        bank: *mut FMOD_STUDIO_BANK,
        path: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_Unload(bank: *mut FMOD_STUDIO_BANK) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_LoadSampleData(bank: *mut FMOD_STUDIO_BANK) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_UnloadSampleData(bank: *mut FMOD_STUDIO_BANK) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetLoadingState(
        bank: *mut FMOD_STUDIO_BANK,
        state: *mut FMOD_STUDIO_LOADING_STATE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetSampleLoadingState(
        bank: *mut FMOD_STUDIO_BANK,
        state: *mut FMOD_STUDIO_LOADING_STATE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetStringCount(
        bank: *mut FMOD_STUDIO_BANK,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetStringInfo(
        bank: *mut FMOD_STUDIO_BANK,
        index: ::std::os::raw::c_int,
        id: *mut FMOD_GUID,
        path: *mut ::std::os::raw::c_char,
        size: ::std::os::raw::c_int,
        retrieved: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetEventCount(
        bank: *mut FMOD_STUDIO_BANK,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetEventList(
        bank: *mut FMOD_STUDIO_BANK,
        array: *mut *mut FMOD_STUDIO_EVENTDESCRIPTION,
        capacity: ::std::os::raw::c_int,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetBusCount(
        bank: *mut FMOD_STUDIO_BANK,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetBusList(
        bank: *mut FMOD_STUDIO_BANK,
        array: *mut *mut FMOD_STUDIO_BUS,
        capacity: ::std::os::raw::c_int,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetVCACount(
        bank: *mut FMOD_STUDIO_BANK,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetVCAList(
        bank: *mut FMOD_STUDIO_BANK,
        array: *mut *mut FMOD_STUDIO_VCA,
        capacity: ::std::os::raw::c_int,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_GetUserData(
        bank: *mut FMOD_STUDIO_BANK,
        userdata: *mut *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_Bank_SetUserData(
        bank: *mut FMOD_STUDIO_BANK,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_IsValid(replay: *mut FMOD_STUDIO_COMMANDREPLAY) -> FMOD_BOOL;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_GetSystem(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        system: *mut *mut FMOD_STUDIO_SYSTEM,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_GetLength(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        length: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_GetCommandCount(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        count: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_GetCommandInfo(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: ::std::os::raw::c_int,
        info: *mut FMOD_STUDIO_COMMAND_INFO,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_GetCommandString(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: ::std::os::raw::c_int,
        buffer: *mut ::std::os::raw::c_char,
        length: ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_GetCommandAtTime(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        time: f32,
        commandindex: *mut ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_SetBankPath(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        bankPath: *const ::std::os::raw::c_char,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_Start(replay: *mut FMOD_STUDIO_COMMANDREPLAY) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_Stop(replay: *mut FMOD_STUDIO_COMMANDREPLAY) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_SeekToTime(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        time: f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_SeekToCommand(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: ::std::os::raw::c_int,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_GetPaused(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        paused: *mut FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_SetPaused(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        paused: FMOD_BOOL,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_GetPlaybackState(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        state: *mut FMOD_STUDIO_PLAYBACK_STATE,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_GetCurrentCommand(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        commandindex: *mut ::std::os::raw::c_int,
        currenttime: *mut f32,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_Release(replay: *mut FMOD_STUDIO_COMMANDREPLAY)
        -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_SetFrameCallback(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        callback: FMOD_STUDIO_COMMANDREPLAY_FRAME_CALLBACK,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_SetLoadBankCallback(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        callback: FMOD_STUDIO_COMMANDREPLAY_LOAD_BANK_CALLBACK,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_SetCreateInstanceCallback(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        callback: FMOD_STUDIO_COMMANDREPLAY_CREATE_INSTANCE_CALLBACK,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_GetUserData(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        userdata: *mut *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
unsafe extern "C" {
    pub fn FMOD_Studio_CommandReplay_SetUserData(
        replay: *mut FMOD_STUDIO_COMMANDREPLAY,
        userdata: *mut ::std::os::raw::c_void,
    ) -> FMOD_RESULT;
}
