/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct g<d> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<d>>,
    pub e: d,
}
