/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cmdline_token_hdr {
    pub ops: *mut cmdline_token_ops,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cmdline_token_ops {
    pub foo: ::std::os::raw::c_int,
}
