/* automatically generated by rust-bindgen 0.71.1 */

pub mod Foo {
    pub type Type = ::std::os::raw::c_uint;
    pub const bar: Type = 0;
    pub const baz: Type = 1;
    pub const blap: Type = 2;
}
unsafe extern "C" {
    #[link_name = "\u{1}__Z4func3Foo"]
    pub fn func(x: Foo::Type);
}
