/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    pub static mut xDlSym: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *const ::std::os::raw::c_char,
        ) -> ::std::option::Option<
            unsafe extern "C" fn(arg1: *const ::std::os::raw::c_char),
        >,
    >;
}
