/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct std___wrap_iter {
    pub _address: u8,
}
pub type std___wrap_iter_iterator_type = u8;
pub type std___wrap_iter_value_type = u8;
pub type std___wrap_iter_difference_type = u8;
pub type std___wrap_iter_pointer = u8;
pub type std___wrap_iter_reference = u8;
pub type std___wrap_iter_iterator_category = u8;
unsafe extern "C" {
    #[link_name = "\u{1}__ZN7MySpace1xE"]
    pub static mut MySpace_x: u64;
}
pub type pointer = pointer;
pub type pointer = type_;
pub type type_ = pointer;
pub type pointer = *mut ::std::os::raw::c_int;
