/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[repr(align(2))]
#[derive(Debug, Copy, Clone)]
pub struct FndrOpaqueInfo {
    pub opaque: [::std::os::raw::c_char; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of FndrOpaqueInfo"][::std::mem::size_of::<FndrOpaqueInfo>() - 16usize];
    ["Alignment of FndrOpaqueInfo"][::std::mem::align_of::<FndrOpaqueInfo>() - 2usize];
    ["Offset of field: FndrOpaqueInfo::opaque"]
        [::std::mem::offset_of!(FndrOpaqueInfo, opaque) - 0usize];
};
