/* automatically generated by rust-bindgen 0.71.1 */

pub const b: _bindgen_ty_1 = 0;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
pub type JS_d = u8;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JS_e {
    pub f: JS_d,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct JS_AutoIdVector {
    pub _base: JS_e,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of JS_AutoIdVector"][::std::mem::size_of::<JS_AutoIdVector>() - 1usize];
    ["Alignment of JS_AutoIdVector"][::std::mem::align_of::<JS_AutoIdVector>() - 1usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of template specialization: JS_e_open0_int_close0"]
        [::std::mem::size_of::<JS_e>() - 1usize];
    ["Align of template specialization: JS_e_open0_int_close0"]
        [::std::mem::align_of::<JS_e>() - 1usize];
};
