/* automatically generated by rust-bindgen 0.71.1 */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    #[repr(C)]
    #[derive(Debug, Copy, Clone)]
    pub struct a {
        pub _address: u8,
    }
    pub mod JS {
        #[allow(unused_imports)]
        use self::super::super::root;
        pub type b = root::a;
        #[repr(C)]
        #[derive(Debug, Copy, Clone)]
        pub struct Rooted {
            pub c: root::JS::b,
        }
    }
}
