/* automatically generated by rust-bindgen */

pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    #[repr(C)]
    #[derive(Debug, Copy)]
    pub struct a {
        pub _address: u8,
    }
    impl Clone for a {
        fn clone(&self) -> Self { *self }
    }
    pub mod JS {
        #[allow(unused_imports)]
        use self::super::super::root;
        pub type b<T> = root::a;
        #[repr(C)]
        #[derive(Debug, Copy, Clone)]
        pub struct Rooted<T> {
            pub c: root::JS::b<T>,
        }
    }
}