/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Inner<T> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<T>>,
    pub foo: T,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Outer {
    pub inner: Inner<T>,
}
