/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    #[link_name = "\u{1}__Z4funcv"]
    pub fn func() -> ::std::option::Option<
        unsafe extern "C" fn(
            arg1: ::std::os::raw::c_int,
            arg2: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >;
}
