/* automatically generated by rust-bindgen 0.71.1 */

pub type void_fn = ::std::option::Option<unsafe extern "stdcall" fn()>;
pub type fn_ =
    ::std::option::Option<unsafe extern "stdcall" fn(id: ::std::os::raw::c_int) -> void_fn>;
