/* automatically generated by rust-bindgen */

pub type void_fn = ::std::option::Option<unsafe extern "stdcall" fn()>;
pub type fn_ = ::std::option::Option<
    unsafe extern "stdcall" fn(
        id: ::std::os::raw::c_int
    ) -> ::std::option::Option<
        unsafe extern "stdcall" fn(id: ::std::os::raw::c_int, ...),
    >,
>;