/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[repr(align(4))]
#[derive(Debug, Copy, Clone)]
pub struct simple {
    pub _bindgen_opaque_blob: [u32; 3usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct templated {
    pub _address: u8,
}
pub type int_tmpl = u8;
