/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Debug, Copy)]
pub struct jvmtiCapabilities {
    pub _bitfield_1: [u16; 8usize],
    pub __bindgen_align: [u32; 0usize],
}
#[test]
fn bindgen_test_layout_jvmtiCapabilities() {
    assert_eq!(::std::mem::size_of::<jvmtiCapabilities>() , 16usize , concat !
               ( "Size of: " , stringify ! ( jvmtiCapabilities ) ));
    assert_eq! (::std::mem::align_of::<jvmtiCapabilities>() , 4usize , concat
                ! ( "Alignment of " , stringify ! ( jvmtiCapabilities ) ));
}
impl Clone for jvmtiCapabilities {
    fn clone(&self) -> Self { *self }
}