/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct globals {
    pub interrupted: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of globals"][::std::mem::size_of::<globals>() - 1usize];
    ["Alignment of globals"][::std::mem::align_of::<globals>() - 1usize];
    ["Offset of field: globals::interrupted"]
        [::std::mem::offset_of!(globals, interrupted) - 0usize];
};
unsafe extern "C" {
    pub static mut interrupted: bool;
}
