/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mystruct {
    pub _address: u8,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mystruct"][::std::mem::size_of::<mystruct>() - 4usize];
    ["Alignment of mystruct"][::std::mem::align_of::<mystruct>() - 1usize];
};
