/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Foo {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Foo_InnerType<T> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<T>>,
    pub t: T,
}
pub type Bar = InnerType;
unsafe extern "C" {
    #[link_name = "\u{1}__Z4funcv"]
    pub fn func() -> Bar;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct InnerType {
    pub _address: u8,
}
