/* automatically generated by rust-bindgen 0.71.1 */

pub const _LIBCPP_ABI_VERSION: u32 = 1;
pub const _LIBCPP_ENABLE_ASSERTIONS_DEFAULT: u32 = 0;
pub const _LIBCPP_ENABLE_HARDENED_MODE_DEFAULT: u32 = 0;
pub const _LIBCPP_ENABLE_DEBUG_MODE_DEFAULT: u32 = 0;
pub const _LIBCPP_VERSION: u32 = 170006;
pub const _LIBCPP_STD_VER: u32 = 14;
pub const _LIBCPP_OBJECT_FORMAT_MACHO: u32 = 1;
pub const _LIBCPP_ENABLE_ASSERTIONS: u32 = 0;
pub const _LIBCPP_ENABLE_HARDENED_MODE: u32 = 0;
pub const _LIBCPP_ENABLE_DEBUG_MODE: u32 = 0;
pub const _LIBCPP_LOCALE__L_EXTENSIONS: u32 = 1;
pub type max_align_t = f64;
pub const A: usize = 5;
