/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Bar {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Foo {
    pub _address: u8,
}
pub type Foo_Getter = ::std::option::Option<unsafe extern "thiscall" fn(arg1: *mut Bar)>;
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Foo"][::std::mem::size_of::<Foo>() - 1usize];
    ["Alignment of Foo"][::std::mem::align_of::<Foo>() - 1usize];
};
unsafe extern "thiscall" {
    #[link_name = "\u{1}?bar@Foo@@QAEXAAVBar@@@Z"]
    pub fn Foo_bar(this: *mut Foo, arg1: *mut Bar);
}
impl Foo {
    #[inline]
    pub unsafe fn bar(&mut self, arg1: *mut Bar) {
        Foo_bar(self, arg1)
    }
}
