/* automatically generated by rust-bindgen 0.71.1 */

pub const MAX: u32 = 1;
pub const A: _bindgen_ty_1 = 0;
pub const B: _bindgen_ty_1 = 1;
pub const MAX: _bindgen_ty_1 = 2;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
