/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct b<a> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<a>>,
    pub _base: a,
    pub d: b<a>,
}
