/* automatically generated by rust-bindgen 0.71.1 */

pub const AV_CODEC_ID_FIRST_UNKNOWN: AVCodecID = 98304;
pub const AV_CODEC_ID_TTF: AVCodecID = 98304;
pub type AVCodecID = ::std::os::raw::c_uint;
