/* automatically generated by rust-bindgen */

pub const AVCodecID_AV_CODEC_ID_TTF: AVCodecID =
    AVCodecID::AV_CODEC_ID_FIRST_UNKNOWN;
#[repr(u32)]
#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum AVCodecID { AV_CODEC_ID_FIRST_UNKNOWN = 98304, }