/* automatically generated by rust-bindgen 0.71.1 */

pub const parameter_t_speed: parameter_t = 0;
pub const parameter_t_acceleration: parameter_t = 1;
#[doc = " The amount of backlash in the system."]
pub const parameter_t_backlash: parameter_t = 2;
#[doc = " The amount of backlash in the system."]
pub const parameter_t_desired_speed: parameter_t = 3;
#[doc = " The amount of backlash in the system."]
pub const parameter_t_position: parameter_t = 4;
#[doc = " The amount of backlash in the system."]
pub const parameter_t_desired_position: parameter_t = 5;
pub type parameter_t = ::std::os::raw::c_uint;
