/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct a<Compare> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<Compare>>,
    pub b: Compare,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AZ_c {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AZ_EBusRouterPolicy {
    pub _address: u8,
}
pub type AZ_EBusRouterPolicy_d = AZ_c;
pub type AZ_EBusRouterPolicy_Container = a<Compare>;
