/* automatically generated by rust-bindgen 0.71.1 */

pub const foo: _bindgen_ty_1 = 4;
pub const bar: _bindgen_ty_1 = 8;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
pub type EasyToOverflow = ::std::os::raw::c_ulonglong;
pub const k: EasyToOverflow = 2147483648;
pub const k_expr: EasyToOverflow = 1152921504606846976;
pub const wow: EasyToOverflow = 2147483648;
pub const BAZ: ::std::os::raw::c_longlong = 24;
pub const fuzz: f64 = 51.0;
pub const BAZZ: ::std::os::raw::c_char = 53;
pub const WAT: ::std::os::raw::c_char = 0;
pub const bytestring: &[u8; 4] = b"Foo\0";
pub const NOT_UTF8: &[u8; 5] = b"\xF0(\x8C(\0";
