/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct foo {
    pub x: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of foo"][::std::mem::size_of::<foo>() - 4usize];
    ["Alignment of foo"][::std::mem::align_of::<foo>() - 1usize];
    ["Offset of field: foo::x"][::std::mem::offset_of!(foo, x) - 0usize];
};
