/* automatically generated by rust-bindgen */

# [ repr ( C ) ]
# [ derive ( Debug , Copy , Clone ) ]
pub struct sqlite3 {
    _unused: [u8; 0],
}
extern "C" {
 # [ link_name = "\u{1}_sqlite3_exec" ]
    ;
}