/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Test {
    pub test: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of Test"][::std::mem::size_of::<Test>() - 4usize];
    ["Alignment of Test"][::std::mem::align_of::<Test>() - 4usize];
    ["Offset of field: Test::test"][::std::mem::offset_of!(Test, test) - 0usize];
};
unsafe extern "C" {
    pub fn test(test: *mut Test);
}
