/* automatically generated by rust-bindgen 0.70.1 */

extern "C" {
    #[link_name = "\u{1}__Z11my_functioni"]
    pub fn my_function(a: ::std::os::raw::c_int);
}
extern "C" {
    #[link_name = "\u{1}__Z11my_functionPKc"]
    pub fn my_function1(a: *const ::std::os::raw::c_char);
}
