/* automatically generated by rust-bindgen */

extern "C" {
    #[link_name = "\u{1}_Z11my_functioni"]
    pub fn my_function(a: ::std::os::raw::c_int);
}
extern "C" {
    pub fn my_function1(a: *const ::std::os::raw::c_char);
}