/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug)]
pub struct std_basic_string<CharT> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<CharT>>,
    pub hider: std_basic_string_Alloc_hider,
    pub length: ::std::os::raw::c_ulong,
    pub __bindgen_anon_1: std_basic_string__bindgen_ty_1<CharT>,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct std_basic_string_Alloc_hider {
    pub storage: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Debug)]
pub struct std_basic_string__bindgen_ty_1<CharT> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<CharT>>,
    pub inline_storage: [CharT; 4usize],
}
