/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
pub struct TransformOp_InterpolateMatrix_Body<A> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<A>>,
    pub from: Transform<TransformOp<A, B, C>>,
    pub to: Transform<TransformOp<A, B, C>>,
    pub a: A,
}
