/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct seal_g<e> {
    pub _phantom_0: ::std::marker::PhantomData<::std::cell::UnsafeCell<e>>,
    pub h: e,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct seal_IntArray {
    pub h: seal_g<e>,
}
