/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct a {
    pub _address: u8,
}
pub type a_b = ::std::os::raw::c_int;
pub type b = ::std::os::raw::c_int;
pub type b = ::std::os::raw::c_int;
