/* automatically generated by rust-bindgen 0.56.0 */
// ...
pub type U8 = ::std::os::raw::c_uchar;
pub type U16 = ::std::os::raw::c_ushort;
#[repr(C)]
#[repr(align(2))]
#[derive(Debug, Default, Copy, Clone)]
pub struct V56AMDY {
    pub _bitfield_1: __BindgenBitfieldUnit<[u8; 2usize], u16>,
    pub MADK: U8,
    pub MABR: U8,
    pub _bitfield_2: __BindgenBitfieldUnit<[u8; 4usize], u16>,
    pub _rB_: U8,
}
#[test]
fn bindgen_test_layout_V56AMDY() {
    assert_eq!(
        ::std::mem::size_of::<V56AMDY>(),
        8usize,
        concat!("Size of: ", stringify!(V56AMDY))
    );
    // ...
}
// ...