/* automatically generated by rust-bindgen */

#[repr(C)]
#[derive(Debug, Copy)]
pub struct Foo {
    pub __bindgen_anon_1: Foo_Bar,
    pub bar: Foo_Bar,
}
#[repr(C)]
#[derive(Debug, Copy)]
pub struct Foo_Bar {
    pub abc: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_Foo_Bar() {
    assert_eq!(::std::mem::size_of::<Foo_Bar>() , 4usize , concat ! (
               "Size of: " , stringify ! ( Foo_Bar ) ));
    assert_eq! (::std::mem::align_of::<Foo_Bar>() , 4usize , concat ! (
                "Alignment of " , stringify ! ( Foo_Bar ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const Foo_Bar ) ) . abc as * const _ as usize }
                , 0usize , concat ! (
                "Alignment of field: " , stringify ! ( Foo_Bar ) , "::" ,
                stringify ! ( abc ) ));
}
impl Clone for Foo_Bar {
    fn clone(&self) -> Self { *self }
}
#[test]
fn bindgen_test_layout_Foo() {
    assert_eq!(::std::mem::size_of::<Foo>() , 4usize , concat ! (
               "Size of: " , stringify ! ( Foo ) ));
    assert_eq! (::std::mem::align_of::<Foo>() , 4usize , concat ! (
                "Alignment of " , stringify ! ( Foo ) ));
    assert_eq! (unsafe {
                & ( * ( 0 as * const Foo ) ) . bar as * const _ as usize } ,
                0usize , concat ! (
                "Alignment of field: " , stringify ! ( Foo ) , "::" ,
                stringify ! ( bar ) ));
}
impl Clone for Foo {
    fn clone(&self) -> Self { *self }
}
