/* automatically generated by rust-bindgen 0.71.1 */

use block;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct contains_ptr_to_block_ptr {
    pub val: *mut _bindgen_ty_id_4,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of contains_ptr_to_block_ptr"]
        [::std::mem::size_of::<contains_ptr_to_block_ptr>() - 8usize];
    ["Alignment of contains_ptr_to_block_ptr"]
        [::std::mem::align_of::<contains_ptr_to_block_ptr>() - 8usize];
    ["Offset of field: contains_ptr_to_block_ptr::val"]
        [::std::mem::offset_of!(contains_ptr_to_block_ptr, val) - 0usize];
};
pub type _bindgen_ty_id_4 = *const ::block::Block<(::std::os::raw::c_int,), ()>;
