/* automatically generated by rust-bindgen 0.71.1 */

#[doc = " This is a constant that has a docstring\n\n And expected to be found in generated bindings code too."]
pub const FOO: ::std::os::raw::c_int = 1;
#[doc = " This is a constant that has a docstring\n\n And expected to be found in generated bindings code too."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Bar {
    pub baz: ::std::os::raw::c_int,
}
