/* automatically generated by rust-bindgen 0.57.0 */

pub const FOO: ::std::os::raw::c_int = 1;
#[doc = " This is a constant that has a docstring"]
#[doc = ""]
#[doc = " And expected be be found in generated bindings code too."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Bar {
    pub baz: ::std::os::raw::c_int,
}
