/* automatically generated by rust-bindgen 0.71.1 */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub mod _bindgen_mod_id_1 {
        #[allow(unused_imports)]
        use self::super::super::root;
        pub mod _bindgen_mod_id_2 {
            #[allow(unused_imports)]
            use self::super::super::super::root;
            #[repr(C)]
            #[derive(Debug, Copy, Clone)]
            pub struct SequentialThreadId {
                pub prevId: u8,
            }
        }
    }
}
