/* automatically generated by rust-bindgen 0.70.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Test {
    pub _address: u8,
}
pub const Test_Enum_One: Test_Enum = 0;
pub const Test_Enum_Two: Test_Enum = 0;
pub type Test_Enum = ::std::os::raw::c_int;
